source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.4'

gem 'active_model_serializers'
gem 'auth0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'carrierwave'
gem 'dockerfile-rails', '>= 1.5', group: :development
gem 'dotenv-rails'
gem 'fog-aws'
gem 'jwt'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rails', '~> 6.1.6', '>= 6.1.6.1'

group :development, :test do
  gem 'debug'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
